### ISSUE TITLE
Document robotDevastation tests

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation-developer-manual#1]
- [ ] testDeadScreen.cpp
- [ ] testDeadState.cpp
- [ ] testFSM.cpp
- [ ] testFSMBuilder.cpp
- [ ] testGameScreen.cpp
- [ ] testGameState.cpp
- [ ] testHUD.cpp
- [ ] testInitScreen.cpp
- [ ] testInitState.cpp
- [ ] testMentalMap.cpp
- [ ] testMockupAudioManager.cpp
- [ ] testMockupInputManager.cpp
- [ ] testMockupNetworkManager.cpp
- [ ] testRdImageManager.cpp
- [ ] testRdInputManager.cpp
- [ ] testRdMockupImageManager.cpp
- [ ] testRdMockupRobotManager.cpp
- [ ] testRdProcessorImageEventListener.cpp
- [ ] testRdYarpImageManager.cpp
- [ ] testRdYarpNetworkManager.cpp
- [ ] testSDLAudioManager.cpp
- [ ] testSDLTextDisplay.cpp

**Comment by David-Estevez** [comment]
Manual tests (the ones that do not use gtest) are the following:

* [ ] testHUD
* [ ] testRdInputManager (that probably should be named "testRdSDLInputManager" instead)
* [ ] testSDLTextDisplay

**Comment by David-Estevez** [comment]
Done!
