### ISSUE TITLE
[robots] Migrate daemontools info to this repo

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation-developer-manual#12]
http://asrob.uc3m.es/index.php/C%C3%B3mo_configurar_el_arranque_del_software_de_RD1_sobre_Raspbian_7 (daemontools info) is linked from https://github.com/asrob-uc3m/robotDevastation-developer-manual/tree/master/robots#notes-about-devices-on-raspi

Should migrate this daemontools info to this repo

**Comment by jgvictores** [comment]
Also see https://github.com/roboticslab-uc3m/installation-guides/blob/master/install-daemontools.md

**Comment by jgvictores** [comment]
>http://asrob.uc3m.es/index.php/C%C3%B3mo_configurar_el_arranque_del_software_de_RD1_sobre_Raspbian_7 (daemontools info)

...was obsolete and is marked as such.

> Also see https://github.com/roboticslab-uc3m/installation-guides/blob/master/install-daemontools.md

Has been linked.

>  https://github.com/asrob-uc3m/robotDevastation-developer-manual/tree/master/robots#notes-about-devices-on-raspi

Has been greatly upgraded, new section URL is now: https://github.com/asrob-uc3m/robotDevastation-developer-manual/tree/master/robots#configure-yarp-devices-as-services-on-raspi

**Comment by jgvictores** [comment]
PS: Specific closing commit was 8b3614ea4bd5af496554da1359f555ab7306004d.

**Comment by PeterBowman** [comment]
Per https://github.com/asrob-uc3m/robotDevastation-robots/blob/6bfe26b456a0f03cb34ebccf6b6c2b9eae662844/scripts/CMakeLists.txt#L7-L10: shouldn't a `git clone && cmake && sudo make install` be enough for having the services installed (as opposed to using `wget`)?

**Comment by jgvictores** [comment]
Yes, I think so. This should be fixed via 66588cd.
